name: VIS 2020
tagline: VAST • INFOVIS • SCIVIS
date: 25-30 October 2020 Virtual Conference
citation_date: May 2020
proceedings_title: Proceedings of the IEEE VIS 2020 Conference
analytics: UA-
logo:
  image: static/images/vis2020_logo_virtual.svg
  width: 250px
  height: auto
# uncomment the following line to show the site title next to the logo image
# site_title: MiniConf
page_title:
  prefix: 'VIS 2020 Virtual'
  separator: ': '
background_image: static/images/salt-lake.jpg
organization: VIS 2020 Organization Committee

# Remove or change to your chat server.
chat_server: miniconf.sloppy.zone
default_presentation_id: 38922815
default_poster_pdf: /static/images/GLTR_poster.pdf


# Configuration for auth
#Test user
#user: miniconf@miniconf.com
#pass: mIniconf1_

use_auth0:
auth0_client_id : JIdr6wi0z27LyLgwkJF0fpk700aj7MNH
auth0_domain : miniconf.auth0.com

calendar:
  colors: #  Colors for the different event hashtags:
    ## from https://coolors.co/264653-2a9d8f-e9c46a-f4a261-e76f51
    ---: '#edf2f7'
    workshop: '#f4a261'
    tutorial: '#e9c46a'
    panel: '#e9c46a'
    live: '#e9c46a'
    associated: '#e76f51'
    visap: '#e76f51'
    application: '#8338ec'
    vis: '#264653'
    memorial: '#264653'
    keynote: '#264653'
    paper: '#2a9d8f'
    papers: '#2a9d8f'
  sunday_saturday: true  #  Include Sunday and Saturday
